export const TIPO_USUARIO = {
    ANFITRION: 'ANFITRION',
    HUESPED: 'HUESPED',
};

export const MONEDAS = {
    DOLAR_USA: 'USD',
    PESO_ARG: 'ARS',
    REAL: 'BRL',
};

export const CARACTERISTICA = {
    WIFI: 'WIFI',
    PISCINA: 'PISCINA',
    MASCOTAS_PERMITIDAS: 'MASCOTAS PERMITIDAS',
    ESTACIONAMIENTO: 'ESTACIONAMIENTO',
};

export const ESTADO_RESERVA = {
    PENDIENTE: 'PENDIENTE',
    CONFIRMADA: 'CONFIRMADA',
    CANCELADA: 'CANCELADA',
};